#!/bin/bash

set -e

cd "$(dirname "$0")/../.."

export DATA_FILE_PATHS=`realpath $PWD/data/synthetic/synthetic_data_canonical.trig`
export PATH=$PATH:$PWD/node_modules/.bin
yarn clean
yarn build

export JEST_CLI_OPTIONS="--updateSnapshot"
script/ts/test
