schema: http://localhost:9000/api/graphql
documents: ./src/ts/*.graphql
overwrite: true
generates:
  ./src/ts/paradicms/gui/generic/api/graphqlFragmentTypes.json:
    plugins:
      - fragment-matcher
