schema: http://localhost:9000/graphql
documents: ./src/ts/*.graphql
overwrite: true
generates:
  ./src/ts/dressdiscover/cms/gui/core/api/graphqlFragmentTypes.json:
    plugins:
      - fragment-matcher
