export {HasAbstract} from "./HasAbstract";
export {HasCreators} from "./HasCreators";
export {HasImages} from "./HasImages";
export {HasInstitution} from "./HasInstitution";
export {HasName} from "./HasName";
export {HasPage} from "./HasPage";
export {HasRelations} from "./HasRelations";
export {HasRights} from "./HasRights";
export {HasTitle} from "./HasTitle";
