#!/bin/bash

set -eu

cd "$(dirname "$0")"
cd ..
echo "Current working directory: $PWD"
export DATA_TTL_FILE_PATH=`realpath $PWD/../etl/data/test_data/loaded/data.ttl`
echo "DATA_TTL_FILE_PATH: $DATA_TTL_FILE_PATH"


yarn install


# Build lib
cd lib
./build.sh

# Test lib
cd rdf
yarn test

cd ..

# Currently in gui/


# Build apps
# Run parallel commands and fail if any of them fails.
cd ../app
pids=()

cd bootstrap-collection
yarn build &
pids+=($!)

cd ..

cd material-ui-union
yarn build &
pids+=($!)

for pid in "${pids[@]}"; do
  wait "$pid"
done
