#!/bin/bash

set -eu

cd "$(dirname "$0")"
cd ..
echo "Current working directory: $PWD"
export DATA_TTL_FILE_PATH=`realpath $PWD/../etl/data/test_data/loaded/data.ttl`
echo "DATA_TTL_FILE_PATH: $DATA_TTL_FILE_PATH"


time yarn install


# Build
wsrun --stages build

# Test
wsrun --exclude-missing test
