export {HasContributors} from "./HasContributors";
export {HasCreators} from "./HasCreators";
export {HasDescription} from "./HasDescription";
export {HasImages} from "./HasImages";
export {HasName} from "./HasName";
export {HasPage} from "./HasPage";
export {HasRelations} from "./HasRelations";
export {HasRights} from "./HasRights";
export {HasTitle} from "./HasTitle";
