name: Build
on: [ push, workflow_dispatch ]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'
      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install Python dependencies
        run: |
          pip install -qqq .[testing]
      - name: Run Python unit tests
        run: |
          mkdir test-results
          pytest --junitxml=test-results/junit.xml
      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-results/*.xml
