name: Build and push Docker image
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Install Node.js and Python dependencies in order to cache them
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.x"
          cache: 'pip'
          cache-dependency-path: |
            lib/py/etl/pyproject.toml
            lib/py/nlp/pyproject.toml
            lib/py/ssg/pyproject.toml
      - run: |
          cd $GITHUB_WORKSPACE/lib/py/etl && pip install -qqq .
          cd $GITHUB_WORKSPACE/lib/py/nlp && pip install -qqq .
          cd $GITHUB_WORKSPACE/lib/py/ssg && pip install -qqq .
          cd $GITHUB_WORKSPACE
          yarn install
          cp -p -R ~/.cache pip-yarn-cache
        name: Install Node.js and Python dependencies locally in order to cache them
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
