name: Build and push Docker image
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-push-etl-docker-image:
    name: Build and push ETL Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        id: docker-login
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build etl Docker image
        needs: docker-login
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/etl/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/etl:latest
