name: Build and push Docker image
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-push-etl-docker-image:
    name: Build and push etl Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/etl/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/etl:latest
  build-push-nlp-docker-image:
    name: Build and push nlp Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/nlp/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/nlp:latest
  build-push-ssg-docker-image:
    name: Build and push ssg Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/ssg/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ssg:latest
