name: Build and test ETL
on:
  push:
    paths:
      - "etl/**"
  workflow_dispatch:
jobs:
  etl:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: etl/.venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('etl/poetry.lock') }}-v2
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: cd etl && poetry install --no-interaction --no-root
      - run: cd etl && poetry run black --check paradicms_etl
      - run: cd etl && poetry run flake8 paradicms_etl
      - run: cd etl && poetry run mypy paradicms_etl
      - name: Run Python unit tests
        run: |
          cd etl
          mkdir test-results
          poetry run pytest --junitxml=test-results/junit.xml
      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: etl/test-results/*.xml
