name: Build and test GUI TypeScript
on:
  push:
    paths-ignore:
      - '.github/workflows/etl.yml'
      - '.github/workflows/gui-py.yml'
      - 'etl/**'
      - 'gui/loader/**'
  workflow_dispatch:
jobs:
  build:
    name: Build and test GUI TypeScript
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: "1"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn dependencies
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('gui/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache Next.js cache
        uses: actions/cache@v2
        with:
          path: gui/app/*/.next/cache
          key: ${{ runner.OS }}-next
      - name: Build and test gui
        run: |
          cd gui
          export PATH=$PATH:$PWD/node_modules/.bin
          yarn install
          export DATA_FILE_PATH=`realpath $PWD/../etl/data/test_data/loaded/data.trig`
          yarn build
          yarn test
      # Commented out to speed up the build
      #      - name: Test gui_loader
      #        run: |
      #          cd etl
      #          pytest --junitxml=test-results/gui_loader.xml test/paradicms_etl_test/loaders/gui/gui_builder_test.py test/paradicms_etl_test/loaders/gui/gui_loader_test.py
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/master'
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
        if: github.ref == 'refs/heads/master'
