name: Build and test GUI Python
on:
  push:
    paths:
      - ".github/workflows/gui-py.yml"
      - "gui/loader/**"
  workflow_dispatch:
jobs:
  build:
    name: Build and test Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: gui/loader/.venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('gui/loader/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: cd gui/loader && poetry install --no-interaction --no-root
      - run: cd gui/loader && poetry run black --check paradicms_gui
      - run: cd gui/loader && poetry run flake8 paradicms_gui
      - run: cd gui/loader && poetry run mypy paradicms_gui
