name: Build and test SSG Python
on:
  push:
    paths:
      - ".github/workflows/lib-py-ssg.yml"
      - "lib/py/ssg/**"
  workflow_dispatch:
jobs:
  build:
    name: Build and test Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9.x"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: lib/py/ssg/.venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('lib/py/ssg/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: cd lib/py/ssg && poetry install --no-interaction --no-root
      - run: cd lib/py/ssg && poetry run black --check paradicms_ssg
      - run: cd lib/py/ssg && poetry run flake8 paradicms_ssg
      - run: cd lib/py/ssg && poetry run mypy paradicms_ssg
