name: Build and test NLP
on:
  push:
    paths:
      - ".github/workflows/lib-py-nlp.yml"
      - "lib/py/etl/**"
      - "lib/py/nlp/**"
  workflow_dispatch:
jobs:
  nlp:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.x"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true
      - name: Install libpoppler
        run: sudo apt-get install -y libpoppler-cpp-dev
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: lib/py/nlp/.venv
          key: venv-v2-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('lib/py/nlp/poetry.lock') }}-v2
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: lib/py/nlp/script/bootstrap
      - run: lib/py/nlp/script/cibuild
      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: lib/py/nlp/test-results/*.xml
