name: Build and test Python
on:
  push:
    paths:
      - "loader/**"
  workflow_dispatch:
jobs:
  build:
    name: Build and test Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: paradicms/etl
          path: etl
      - uses: actions/checkout@v3
        with:
          path: gui
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: gui/.venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
#        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: cd gui/loader && poetry install --no-interaction --no-root
      - run: cd gui/loader && poetry run black --check paradicms_gui
      - run: cd gui/loader && poetry run flake8 paradicms_gui
      - run: cd gui/loader && poetry run mypy paradicms_gui
