name: Build and test TypeScript
on:
  push:
    paths:
      - ".github/workflows/ts.yml"
      - "app/**"
      - "data/**"
      - "lib/ts/**"
      - "package.json"
      - "tsconfig.base.json"
      - "yarn.lock"
  workflow_dispatch:
jobs:
  build:
    name: Build and test TypeScript
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: "1"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 16
      - name: Cache Next.js cache
        uses: actions/cache@v3
        with:
          path: app/*/.next/cache
          key: ${{ runner.OS }}-next
      - name: Build and test TypeScript
        run: |
          export PATH=$PATH:$PWD/node_modules/.bin
          yarn install
          export DATA_FILE_PATH=`realpath $PWD/data/test_data/loaded/data.trig`
          yarn build
          yarn test
