name: Build and test TypeScript
on:
  push:
    paths:
      - '.github/workflows/etl.yml'
      - '.github/workflows/ssg.yml'
      - 'app/**'
      - 'lib/ts/**'
  workflow_dispatch:
jobs:
  build:
    name: Build and test TypeScript
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: "1"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn dependencies
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache Next.js cache
        uses: actions/cache@v2
        with:
          path: app/*/.next/cache
          key: ${{ runner.OS }}-next
      - name: Build and test TypeScript
        run: |
          export PATH=$PATH:$PWD/node_modules/.bin
          yarn install
          export DATA_FILE_PATH=`realpath $PWD/data/test_data/loaded/data.trig`
          yarn build
          yarn test
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref == 'refs/heads/master'
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
        if: github.ref == 'refs/heads/master'
