name: Build and test TypeScript
on:
  push:
    paths:
      - ".github/workflows/ts.yml"
      - "app/**"
      - "data/synthetic/**"
      - "lib/ts/**"
      - "package.json"
      - "tsconfig.base.json"
      - "yarn.lock"
  workflow_dispatch:
env:
  NODE_OPTIONS: "--max-old-space-size=4096"
jobs:
  build:
    name: Build and test TypeScript
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 20
      - name: Cache Next.js cache
        uses: actions/cache@v4
        with:
          path: app/*/.next/cache
          key: ${{ runner.OS }}-next
      - name: Install dependencies
        run: script/ts/bootstrap
      - name: Build and test TypeScript
        run: script/ts/cibuild
